config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :clients
  resources :appointments
  resources :locations do
    resources :appointments, only: [:index, :show, :new]
  end
  resources :clients do
    resources :appointments, only: [:index, :show, :new]
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  get 'welcome/home'
  root 'welcome#home'

  get '/about', to: 'welcome#about'

  get '/locations/:id/client_list', to: 'locations#client_list', as: 'client_list'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
    belongs_to :location
    belongs_to :user
    belongs_to :client

    accepts_nested_attributes_for :client
    accepts_nested_attributes_for :location

    def start_time
      self.appointment_time
    end

    def end_time
      appointment_time + duration.seconds
    end

    def client_name
      client.name
    end

    def location_name
      location.nickname if location
    end

    # parse form methods

    def client_attributes=(attr)
      if attr[:name] != ""
        self.client = self.user.clients.find_or_create_by(attr)
      end
    end

    def location_attributes=(attr)
      if attr[:nickname] != ""
        location = self.user.locations.find_or_create_by(attr)
        self.location = location
      end
    end

    #custom setter called upon receving a hash(mass assignment) from the appointment#create actions, also accepts a time object for testing
    #when called on a hash the parse_datetime method is called on the hash to produce a datetime object that can be save in DB 
    def appointment_time=(time)
      if time.is_a?(Hash)
        self[:appointment_time] = parse_datetime(time)
      else
        self[:appointment_time] = time
      end
    end

    def parse_date(string)
      array = string.split("/")
      first_item = array.pop
      array.unshift(first_item).join("-")
    end

    def parse_datetime(hash)
      if hash["date"].match(/\d{2}\/\d{2}\/\d{4}/)
        Time.zone.parse("#{parse_date(hash["date"])} #{hash["hour"]}:#{hash["min"]}")
      end
    end

    def duration=(duration)
      if duration.is_a?(Hash)
        self[:duration] = parse_duration(duration)
      else
        self[:duration] = duration
      end
    end

    def parse_duration(hash)
      hash["hour"].to_i + hash["min"].to_i
    end

    # Validations

    validates :duration, presence: true, numericality: { greater_than_or_equal_to: 0 }
    validates :appointment_time, presence: { message: "must be a valid date" }
    validates :price, numericality: { greater_than_or_equal_to: 0 }, allow_blank: true
    validates :client_id, presence: true

    validate :time_still_valid

    def time_still_valid
      AppointmentTimeValidator.new(self).validate
    end

    include ActiveModel::Validations

    class AppointmentTimeValidator
      def initialize(appointment)
        @appointment = appointment
        @user = appointment.user
      end

      def validate
        if @appointment.appointment_time
          # selects the user's appointments from yesterday, today and tomorrow
          appointments = @user.appointments.select { |a| a.appointment_time.midnight == @appointment.appointment_time.midnight || a.appointment_time.midnight == @appointment.appointment_time - 1.day || a.appointment_time.midnight == @appointment.appointment_time + 1.day }
          # makes sure that current appointments don't overlap and checks if an existing appointment is still in progress when the new appointment is set to start
          # then checks if the new appointment would still be going on when an existing appointment is set to start
          appointments.each do |appointment|
            if @appointment != appointment
              if appointment.appointment_time <= @appointment.appointment_time && @appointment.appointment_time <= appointment.end_time || @appointment.appointment_time <= appointment.appointment_time && appointment.appointment_time <= @appointment.end_time
                @appointment.errors.add(:appointment_time, "is not available.")
              end
            end
          end
        end
      end
    end

    validate do |appointment|
      AppointmentTimeValidator.new(appointment).validate
    end

  end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  before_action :set_appointments, only: [:index, :show, :edit]
  before_action :set_client, only: [:index, :new, :edit]
  before_action :set_location, only: [:index, :new, :edit]

  def index
    @upcoming_appointments = current_user.upcoming_appointments
  end

  def show
  end

  def new
    @appointments = current_user.appointments.select { |a| a.persisted? }
    @appointment = current_user.appointments.build
  end

  def create
    @appointment = Appointment.new(appointment_params.merge(user_id: current_user.id))
    if @appointment.valid?
      @appointment.save
      redirect_to appointments_path
    else
      @appointment.user = nil
      @appointments = current_user.appointments.select { |a| a.persisted? }
      render :new
    end
  end

  def edit
  end

  def update
    if @appointment.update(appointment_params)
      redirect_to appointments_path
    else
      set_appointments
      render :edit
    end
  end

  def destroy
    @appointment.destroy
    redirect_to appointments_path
  end

  private

  def set_client
    @client = current_user.clients.find_by(id: params[:client_id])
  end

  def set_location
    @location = current_user.locations.find_by(id: params[:location_id])
  end

  def set_appointment
    @appointment = current_user.appointments.find_by(id: params[:id])
    if @appointment.nil?
      flash[:error] = "Appointment not found."
      redirect_to appointments_path
    end
  end

  def set_appointments
    @appointments = current_user.appointments.order(appointment_time: :desc)
  end

  def appointment_params
    params.require(:appointment).permit(:client_id, :price, :location_id, location_attributes: [:nickname], client_attributes: [:name], appointment_time: [:date, :hour, :min], duration: [:hour, :min])
  end
end

app/views/appointments/_appointment.html.erb
<div class="appointment">
  <%= appointment_heading(appointment) %>
  <%= appointment_details(appointment) %>
  <%= appointment_edit_delete_links(appointment) %>
</div>

app/views/appointments/_appointment_details.html.erb
<p><%= full_time(appointment) %></p>
<p>Duration: <%= show_duration(appointment) %></p>
<%= show_price(appointment) %>
<%= show_location(appointment) %>

app/views/appointments/_appointment_short.html.erb
<h4><%= link_to appointment.client_name, appointment_path(appointment) %>, <%= short_time(appointment) %>-<%= end_time(appointment) %></h4>

app/views/appointments/_client_fields.html.erb
<% if current_user.clients.any? %>
<div class="field">
  <p>
    <%= label_tag :client %>
    <%= collection_select :appointment, :client_id, current_user.clients, :id, :name, { prompt: true } %>
  </p>
</div>
<% end %>
<p>
  <% if current_user.clients.any? %>Or <% end %>Create a New Client
</p>
<div class="field">
  <%= f.fields_for :client, Client.new do |ff| %>
  <%= ff.label :name %>
  <%= ff.text_field :name %>
  <% end %>
</div>

app/views/appointments/_form.html.erb
<%= render partial: "layouts/errors", locals: { object: appointment } %>
<%= form_for appointment do |f| %>
  <%= client_fields(f, appointment, client) %>
  <div class="field">
    <p>
      <%= label_tag "appointment[appointment_time][date]", "Date" %>
      <%= text_field_tag "appointment[appointment_time][date]", appointment_date(appointment) %>
    </p>
  </div>
  <div class="field">
    <p id="time">
      <%= label_tag "appointment[appointment_time][hour]", "Time" %>
      <%= hour_selector("appointment[appointment_time][hour]", appointment) %> :
      <%= min_selector("appointment[appointment_time][min]", appointment) %>
    </p>
  </div>
  <div class="field">
    <p>
      <%= f.label :duration %>
      <%= duration_hour_field("appointment[duration][hour]", appointment) %>
      <%= duration_minute_field("appointment[duration][min]", appointment) %>
    </p>
  </div>
  <div class="field">
    <p>
      <%= f.label :price %>
      <%= f.number_field :price, step: 0.25, value: float_two_decimals(appointment.price) %>
    </p>
  </div>
  <%= location_fields(f, appointment, location) %>
  <p><%= f.submit %></p>
<% end %>

app/views/appointments/_location_fields.html.erb
<% if current_user.locations.any? %>
<div class="field">
  <p>
    <%= f.label :location_id %>
    <%= collection_select :appointment, :location_id, current_user.locations, :id, :nickname, {prompt: true } %>
  </p>
</div>
<% end %>
<p><% if current_user.locations.any? %>Or <% end %>Create a New Location</p>
<div class="field">
  <p>
    <%= f.fields_for :location, Location.new do |location_attr| %>
      <%= location_attr.label :nickname %>
      <%= location_attr.text_field :nickname %>
    <% end %>
  </p>
</div>

app/views/appointments/edit.html.erb
<div class="row">
  <div class="col-md-4">
    <h1>Edit Appointment</h1>
    <%= render partial: "form", locals: { appointment: @appointment, client: @client, location: @location } %>
    <p>
      <%= link_to "Delete", @appointment, method: :delete, data: { confirm: "Are you sure you want to delete this appointment?" } %>
    </p>
  </div>
  <div class="col-md-8">
    <%= add_weekly_calendar(@appointments) %>
  </div>
</div>

app/views/appointments/index.html.erb
<h1>Appointments</h1>
<%= link_to "Make a new appointment", new_appointment_path %>
<%= add_weekly_calendar(@appointments) %>

<h3>Upcoming Appointments</h3>
<% if @upcoming_appointments.any? %>
  <%= render @upcoming_appointments %>
<% else %>
  <p>No appointments yet.</p>
<% end %>

app/views/appointments/new.html.erb
<div class="row">
  <div class="col-md-4">
    <h1>New Appointment</h1>
    <%= render partial: 'form', locals: { appointment: @appointment, client: @client, location: @location } %>
  </div>
  <div class="col-md-8">
    <%= add_weekly_calendar(@appointments) %>
  </div>
</div>

app/views/appointments/show.html.erb
<%= add_weekly_calendar(@appointments) %>
<h1>Appointment</h1>
<%= render @appointment %>