config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :clients
  resources :appointments
  resources :locations do
    resources :appointments, only: [:index, :show, :new]
  end
  resources :clients do
    resources :appointments, only: [:index, :show, :new]
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  get 'welcome/home'
  root 'welcome#home'

  get '/about', to: 'welcome#about'

  get '/locations/:id/client_list', to: 'locations#client_list', as: 'client_list'

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user
  has_many :appointments, dependent: :destroy
  has_many :clients, through: :appointments

  def client_count
    clients.count
  end

  def appointment_count
    appointments.count
  end

  def value
    appointments.collect { |a| a.price }.compact.inject(0, :+)
  end

  validates :nickname, presence: true


end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_location, only: [:client_list, :show, :edit, :update, :destroy]

  def index
    @locations = current_user.locations
  end

 def client_list
   @clients = @location.clients
 end

 def show
   @appointments = @location.appointments
 end

 def new
   @location = Location.new
 end

 def create
   @location = Location.new(location_params)
   if @location.valid?
     @location.user = current_user
     @location.save
     redirect_to locations_path
   else
     render :new
   end
 end

 def edit
 end

 def update
   if @location.update(location_params)
     redirect_to location_path(@location)
   else
     render :edit
   end
 end

 def destroy
   @location.destroy
   redirect_to locations_path
 end

 private

 def set_location
   @location = current_user.locations.find_by(id: params[:id])
   if @location.nil?
     flash[:error] = "Location not found."
     redirect_to locations_path
   end
 end

 def location_params
   params.require(:location).permit(:nickname, :street_address, :city, :state, :zipcode, :business_name)
 end

end

app/helpers/locations_helper.rb
module LocationsHelper

  def show_street_address(location)
    location.street_address if location.street_address
  end

  def city_state_zip(location)
    "#{location.city}, #{location.state} #{location.zipcode}" if location.city && location.state && location.zipcode
  end

  def show_nickname(location)
    if current_page?(location_path(location))
      location.nickname
    else
      link_to location.nickname, location_path(location)
    end
  end

  def show_address(location)
    render partial: "locations/address", locals: { location: location }
  end

  def edit_delete_links(location)
    output = [
      link_to("Edit,", edit_location_path(location), class: "btn btn-secondary"),
      link_to(" Delete", location, method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you want to delete location" })
    ]
    safe_join(output)
  end

  def appointment_count(location)
    link_to pluralize(location.appointment_count, 'appointment'), location_path(location)
  end

  def location_value(location)
    number_to_currency(location.value) if location.value != 0
  end

  def client_count(location)
    link_to pluralize(location.client_count, 'client'), client_list_path(location)
  end

end

app/views/locations/_address.html.erb
<p><%= location.business_name %></p>
<p><%= show_street_address(location) %></p>
<p><%= city_state_zip(location) %></p>

app/views/locations/_form.html.erb
<%= render partial: "layouts/errors", locals: { object: location } %>
<%= form_for location do |f| %>
  <p>
    <%= f.label :nickname %>
    <%= f.text_field :nickname %>
  </p>
  <p>
    <%= f.label :street_address %>
    <%= f.text_field :street_address %>
  </p>
  <p>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </p>
  <p>
    <%= f.label :zipcode %>
    <%= f.text_field :zipcode %>
  </p>
  <p>
    <%= f.label :business_name %>
    <%= f.text_field :business_name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/locations/_location.html.erb
<div class="location">
  <h2><%= show_nickname(location) %></h2>
  <%= show_address(location) %>
  <p><%= appointment_count(location) %></p>
  <p><%= location_value(location) %></p>
  <p><%= edit_delete_links(location) %></p>
</div>

app/views/locations/_location_index.html.erb
<div class="location row">
  <div class="col-sm-3">
    <p class="name"><%= show_nickname(location) %></p>
    <p><%= edit_delete_links(location) %></p>
  </div>
  <div class="col-sm-3">
    <%= show_address(location) %>
  </div>
  <div class="col-sm-3">
    <p><%= client_count(location) %></p>
  </div>
  <div class="col-sm-3">
    <p><%= appointment_count(location) %></p>
    <p><%= location_value(location) %></p>
    <!-- <p><%= link_to "Add Appointment", new_location_appointment_path(location), class: "btn btn-primary" %></p> -->
  </div>
</div>

app/views/locations/client_list.html.erb
<h1>Client List</h1>
<h3>Location</h3>
<h5><%= link_to @location.nickname, location_path(@location) %></h5>
<p><%= show_address(@location) %></p>

<h3>Clients</h3>
<ul>
  <% @clients.each do |client| %>
    <li><%= link_to client.name, client_path(client) %></li>
  <% end %>
</ul>

app/views/locations/edit.html.erb
<h1>Edit Location</h1>
<%= render partial: "form", locals: { location: @location } %>

app/views/locations/index.html.erb
<h1>Locations</h1>
<%= link_to "Add a Location", new_location_path %>
<% if @locations.any? %>
<% else %>
<p>No locations yet.</p>
<% end %>
<div class="locations">
  <%= render partial: "location_index", collection: @locations, as: :location %>
</div>

app/views/locations/new.html.erb
<h1>New Location</h1>
<%= render partial: "form", locals: { location: @location } %>

app/views/locations/show.html.erb
<h1>Location</h1>
<%= render @location %>
<h1>Appointments</h1>
<%= link_to "Make a new appointment", new_location_appointment_path(@location) %>
<%= render @appointments, template: "appointments/appointment" %>