config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :clients
  resources :appointments
  resources :locations do
    resources :appointments, only: [:index, :show, :new]
  end
  resources :clients do
    resources :appointments, only: [:index, :show, :new]
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  get 'welcome/home'
  root 'welcome#home'

  get '/about', to: 'welcome#about'

  get '/locations/:id/client_list', to: 'locations#client_list', as: 'client_list'

end

app/views/layouts/_errors.html.erb
<% if object && object.errors.any? %>
  <h2><%= "#{object.errors.full_messages.uniq.count} error(s):" %></h2>
  <ul>
  <% object.errors.full_messages.uniq.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="container">
    <ul class="main-menu">
      <li><%= link_to "Home", root_path %></li>
    <% if user_signed_in? %>
     <li><%= link_to "Appointments", appointments_path %></li>
      <li><%= link_to "Clients", clients_path %></li>
      <li><%= link_to "Locations", locations_path %></li>
      <li class="right"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li class="left"><%= link_to "Sign in", new_user_session_path %></li>
      <li class="left"><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %></li>
      <li class="left"><%= link_to "Sign up", new_user_registration_path %></li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppointmentBook</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">

 <%= render "layouts/navbar" %>

 <%= content_tag(:div, flash[:error], id: "flash_error", class: "container") if flash[:error] %>
 <%= content_tag(:div, flash[:notice], id: "flash_notice", class: "container") if flash[:notice] %>
 <%= content_tag(:div, flash[:alert], id: "flash_alert", class: "container") if flash[:alert] %>

 <div class="main container">
   <%= yield %>
 </div>
</body>
</html>